version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    ports: 
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4576:4576"
      - "4571:4571"
      - "8001:8001"
    environment:
      HOSTNAME: localstack
      DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: local_key
      AWS_SECRET_ACCESS_KEY: local_key
      DATA_DIR: /tmp/localstack/data
      EDGE_PORT: 4566
      DEBUG: 1
      SERVICES: apigateway,cloudformation,cloudwatch,cloudwatchevents,dynamodb,ec2,es,firehose,iam,kinesis,lambda,route53,redshift,s3,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts,ecr
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"