version: "3.9"

services:
  localstack:
    image: localstack/localstack
    ports: 
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4576:4576"
      - "4571:4571"
      - "8001:8001"
    volumes:
      - type: volume
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      SERVICES: cloudformation,kms,lambda,iam,s3,sqs
      HOSTNAME: localstack
      DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: local_key
      AWS_SECRET_ACCESS_KEY: local_key
      DATA_DIR: /tmp/localstack/data

volumes:
    localstack_data:
